import { Disclosure, GrowthPageShell, GrowthSection, InlineLink, TextLinks, Topic, TopicGrid, type Faq } from "./shared";

const faqs: Faq[] = [
  { question: "What is the cheapest Northstar website package?", answer: "Northstar’s current Starter Static Website is ₱15,000 for the published base scope. It is designed for a small business needing a credible website and direct contact links without a contact form or backend system." },
  { question: "Is domain registration included in the website price?", answer: "No. Northstar clients purchase and own their domain. Domain purchase, connection, renewal, and other provider costs are handled according to the approved proposal." },
  { question: "Does the website price include hosting?", answer: "Northstar’s current starter and business packages list free-tier deployment. A paid hosting or deployment plan may be required when traffic, storage, functions, support, provider requirements, or other needs exceed the appropriate free tier. Confirm the current scope before approval." },
  { question: "How much is a website with online booking in the Philippines?", answer: "Northstar’s Booking Website currently starts at ₱50,000 for the stated base scope. The final quote depends on pages, provider, services, staff or resources, availability flow, reminders, payments, data, and other requirements. Provider subscriptions and transaction fees are separate." },
  { question: "How much is a resort reservation website?", answer: "Northstar’s Hotel and Resort Reservation Website currently starts at ₱72,000. Room or package structure, content, provider connections, availability, payments, policies, and data-entry requirements affect the final scope." },
  { question: "Is SEO included in a Northstar website?", answer: "Northstar’s current website packages include basic SEO foundations appropriate to their stated scope, such as page structure and metadata setup. This does not guarantee rankings, traffic, leads, or sales. Ongoing keyword research, content production, authority building, and performance analysis are separate growth activities." },
  { question: "Can I add more features later?", answer: "Yes, when the existing architecture and selected providers support them. Future pages, integrations, automation, booking, payments, or operational systems should be scoped and approved separately rather than assumed to be included in the original package." },
  { question: "Why can two developers quote very different prices for the same website?", answer: "The scopes may not actually be the same. Differences can include page count, custom design, content work, forms, integrations, revisions, testing, ownership, training, support, technology, experience, and excluded third-party costs. Compare written deliverables and responsibilities, not just the total." },
];

export function WebsiteCostGuidePage({ nonce }: { nonce?: string }) {
  return <GrowthPageShell
    path="/guides/business-website-cost-philippines"
    kind="article"
    eyebrow="2026 PRICING GUIDE"
    title="How Much Does a Business Website Cost in the Philippines?"
    description="See Northstar’s current website starting prices, what each package includes, separate provider costs, and the factors that affect a Philippine website quote."
    intro={<><p>A business website can cost <strong>₱15,000 for a focused Northstar starter site</strong>, <strong>₱25,000 for a Northstar business website with a contact form</strong>, or more when the project includes booking, reservations, payments, custom workflows, extensive content, or third-party integrations.</p><p>Those figures are Northstar Systems’ current starting prices—not a claim about the entire Philippine web-development market. Other providers may quote less or more because their scope, process, support, technology, ownership terms, and excluded costs differ.</p><p>The useful question is not simply, “How much is a website?” It is:</p><blockquote>What must this website help customers and staff do, and what is included in the quoted price?</blockquote><p>This guide explains Northstar’s current packages, what changes a website quote, which costs may remain separate, and how a Philippine business can choose a sensible first phase.</p><p className="growth-review-date"><strong>By:</strong> Northstar Systems<br/><strong>Last reviewed:</strong> August 2026<br/><strong>Pricing note:</strong> Confirm current package details before publishing or approving a proposal. Northstar Systems reviews the guide against the Packages page whenever starting prices or package scopes change and updates the visible review date and structured <code>dateModified</code>.</p></>}
    breadcrumbs={[{ name: "Home", href: "/" }, { name: "Guides", href: "/guides/business-website-cost-philippines" }, { name: "Business Website Cost Philippines", href: "/guides/business-website-cost-philippines" }]}
    faqs={faqs}
    nonce={nonce}
    secondaryCta={{ label: "Compare solution packages", href: "/packages" }}
    finalTitle="Get a focused recommendation for your business."
    finalCopy="Tell Northstar what the website needs to help customers and staff do. We will review the current workflow, identify a practical first phase, and explain which costs belong to Northstar and which remain with third-party providers."
    finalSecondary={{ label: "Explore website services", href: "/services/websites" }}
  >
    <GrowthSection title="The short answer: the price depends on the job the website must do.">
      <p>A small website that introduces a business and directs visitors to Facebook, email, or WhatsApp is a different product from a website that receives validated inquiries, checks a provider’s appointment slots, collects reservation details, requests a deposit, or connects to an operational system.</p>
      <p>Price changes when the project adds responsibility. A website becomes more complex when it must:</p>
      <ul><li>Present more pages, services, products, rooms, or locations</li><li>Organize or create substantial content</li><li>Receive and deliver customer information</li><li>Connect to a booking, payment, messaging, POS, or inventory provider</li><li>Apply business rules</li><li>Support staff accounts or permissions</li><li>Import existing records</li><li>Produce reports or exports</li><li>Meet a defined support or maintenance requirement</li></ul>
      <p>A responsible quote should separate the base website from client-owned providers, future work, and advanced operational systems.</p>
    </GrowthSection>

    <GrowthSection title="Northstar’s current website starting prices." className="growth-tinted">
      <p>The prices below reflect Northstar Systems’ published base packages at the time this guide was reviewed. The listed amount covers the stated scope. Additional pages, integrations, data entry, provider setup, content work, and operational requirements are quoted before approval.</p>
      <div className="growth-table-wrap" tabIndex={0} role="region" aria-label="Northstar website package pricing"><table><thead><tr><th>Northstar package</th><th>Current starting price</th><th>Best suited to</th></tr></thead><tbody><tr><td>Starter Static Website</td><td>₱15,000</td><td>A small business needing a credible online presence and direct contact links</td></tr><tr><td>Business Website</td><td>₱25,000</td><td>A business needing a more complete site and delivered inquiry form</td></tr><tr><td>Booking Website</td><td>From ₱50,000</td><td>Appointment-led businesses using an appropriate booking provider</td></tr><tr><td>Hotel &amp; Resort Reservation Website</td><td>From ₱72,000</td><td>Properties needing room/package presentation and an honest reservation workflow</td></tr></tbody></table></div>
      <TopicGrid>
        <Topic title="Starter Static Website — ₱15,000"><p>This package is for a small business that needs a clean, credible online presence without a contact-form backend or connected operational system.</p><p>The current base scope includes:</p><ul><li>A small static website with agreed pages</li><li>Responsive desktop and mobile design</li><li>Facebook, email, or WhatsApp contact links</li><li>Basic SEO foundations</li><li>One revision round</li><li>Free-tier deployment</li></ul><p>The client supplies the approved copy, photos, and logo. The package does not include a contact form or lead storage. Domain purchase and connection are billed separately, and future updates or paid providers are not included.</p><p>This can be the right choice when the main goal is to explain the business clearly and direct visitors to a contact channel the team already monitors.</p><TextLinks><InlineLink href="/packages">View the Starter Static Website on the Packages page.</InlineLink></TextLinks></Topic>
        <Topic title="Business Website — ₱25,000"><p>This package is for businesses that need a more complete website and a dependable way to receive inquiries.</p><p>The current base scope includes:</p><ul><li>Up to five pages</li><li>More customized responsive design</li><li>A working contact form</li><li>Direct-contact and map integrations</li><li>Two revision rounds</li><li>Form validation and basic spam protection</li><li>Light organization of client-provided content</li><li>Basic SEO and social-sharing setup</li><li>Free-tier deployment</li><li>Form delivery tested with the client inbox</li></ul><p>Paid form or email services are quoted separately when required.</p><p>This package is usually a stronger fit when the website must do more than send visitors to social media. It gives the business a structured place to explain services, build trust, and receive qualified inquiries.</p><TextLinks><InlineLink href="/services/websites">Explore Northstar website design and development.</InlineLink></TextLinks></Topic>
        <Topic title="Booking Website — from ₱50,000"><p>This package is designed for appointment-led businesses such as clinics, salons, consultants, and rentals using an appropriate booking provider.</p><p>The current base scope includes:</p><ul><li>Up to seven website pages</li><li>Booking-provider integration</li><li>Service, staff, date, and time selection when supported</li><li>Customer-information collection</li><li>Contact form and direct-contact links</li><li>Testing, training, and handover</li><li>Confirmations and reminders when supported by the provider</li></ul><p>The booking-provider subscription is paid by the client. Deposits, payments, messaging, or additional provider work are quoted separately.</p><p>The phrase “from ₱50,000” matters. A simple provider connection is not the same as a custom scheduling platform, multi-location resource system, complex membership workflow, or large data migration.</p><TextLinks><InlineLink href="/services/booking">Explore online booking systems.</InlineLink></TextLinks></Topic>
        <Topic title="Hotel and Resort Reservation Website — from ₱72,000"><p>A hotel or resort site normally needs more content and a more careful reservation journey than a standard appointment website.</p><p>The current starting scope can cover:</p><ul><li>Room or package presentation</li><li>Check-in and check-out flow</li><li>Guest and reservation details</li><li>Property-approved policies and information</li><li>An honest availability or inquiry workflow</li></ul><p>Deposits, payment processing, provider connections, channel-management requirements, extensive room data, additional content, and other operational needs are quoted separately.</p><p>Live availability should only be promised when a supported authoritative inventory source is connected and tested. Otherwise, the site should use a request-to-book or availability-inquiry flow.</p><TextLinks><InlineLink href="/industries/resorts-hotels">Explore resort and hotel website design.</InlineLink></TextLinks></Topic>
      </TopicGrid>
    </GrowthSection>

    <GrowthSection title="What changes the cost of a business website?">
      <TopicGrid>
        <Topic title="Number and complexity of pages"><p>A five-page business site requires less design, content preparation, review, and testing than a site with dozens of service, product, room, location, or resource pages.</p><p>Page count is not the only factor. A simple contact page is different from a detailed service page with custom illustrations, comparison tables, calculators, interactive components, or structured content that staff must maintain.</p><p>Before accepting a quote, ask whether the page allowance refers to unique designed pages, repeated templates, or both.</p></Topic>
        <Topic title="Content, photography, and branding"><p>A developer can build the page structure, but the website still needs accurate words, images, logos, service details, policies, and calls to action.</p><p>A lower quote may assume the client will provide finished content in the required format. Costs can rise when the project needs:</p><ul><li>Professional copywriting</li><li>Content interviews and research</li><li>Brand strategy or visual identity</li><li>Logo work</li><li>Photography or video</li><li>Image sourcing and licensing</li><li>Significant rewriting or content entry</li><li>Translation or multilingual review</li></ul><p>Northstar’s current base packages rely on client-provided materials with the level of organization stated in each scope. Professional copywriting, branding, and extensive content work are quoted separately.</p></Topic>
        <Topic title="Forms and lead delivery"><p>A direct email or Messenger link is simpler than a contact form that validates entries, filters spam, sends notifications, stores consent, handles errors, and is tested against the client’s inbox.</p><p>Ask what happens after someone submits the form:</p><ul><li>Where is the inquiry sent?</li><li>Is delivery tested?</li><li>Is there a success and error state?</li><li>Is spam protection included?</li><li>Is information stored anywhere?</li><li>Who owns the form or email account?</li><li>Are paid sending services required?</li></ul></Topic>
        <Topic title="Booking, payment, and provider integrations"><p>Integrations add cost because the website must work within another provider’s capabilities, account permissions, commercial terms, documentation, and technical limits.</p><p>A quote should identify:</p><ul><li>Which provider is being used</li><li>Who owns and pays for the account</li><li>Which exact steps are connected</li><li>Whether availability is live or request-based</li><li>Whether confirmation is automatic or staff-reviewed</li><li>Which reminders or messages are supported</li><li>Whether deposits or payments are included</li><li>Which transaction or messaging fees remain separate</li></ul><p>“Booking system included” is not enough detail for a reliable comparison.</p></Topic>
        <Topic title="Product, inventory, or operational requirements"><p>A product catalog on a website is not automatically a POS or inventory system. Displaying products, receiving an order request, processing checkout, deducting stock, handling returns, managing cashier shifts, and producing operational reports are separate responsibilities.</p><p>Northstar normally recommends an appropriate established POS or inventory provider first. Existing POS or inventory integration currently starts at ₱15,000 when the selected provider supports the required connection.</p><p>Advanced internal systems are separate products rather than small website add-ons. Northstar’s current published starting prices include:</p><ul><li>Custom Inventory System — from ₱90,000</li><li>Custom POS System — from ₱180,000</li></ul><p>These figures apply only to their stated starting scopes. Users, locations, compliance, hardware, migration, support, and integrations can materially change the final proposal.</p><TextLinks><InlineLink href="/services/pos-inventory">Explore POS and inventory implementation.</InlineLink><InlineLink href="/services/custom-software-development">Explore custom software development.</InlineLink></TextLinks></Topic>
        <Topic title="Data entry and migration"><p>A website quote may include the page templates but not the work of entering hundreds of products, rooms, services, customer records, stock items, or historical transactions.</p><p>Existing data may also require cleaning, mapping, deduplication, formatting, and client review before it can be imported safely.</p><p>Ask for a written allowance and responsibility list:</p><ul><li>How many records or items are included?</li><li>Who prepares the source files?</li><li>Who checks accuracy?</li><li>Is historical data required?</li><li>What happens to incomplete or duplicate records?</li><li>Is migration testing included?</li></ul></Topic>
        <Topic title="Revisions, training, and support"><p>More revision rounds, stakeholder reviews, training sessions, documentation, and post-launch support add real work.</p><p>A clear proposal should state:</p><ul><li>Number and type of revisions included</li><li>Who consolidates client feedback</li><li>What counts as a new requirement</li><li>Which users receive training</li><li>What handover materials are included</li><li>How launch issues are handled</li><li>Whether maintenance is included or separate</li></ul><p>Northstar’s website packages specify their included revision rounds. Ongoing maintenance is available under a separate support plan.</p></Topic>
      </TopicGrid>
    </GrowthSection>

    <GrowthSection title="Costs that may be separate from the website quote." className="growth-dark">
      <p>The build price is not always the full operating cost. Northstar’s clients purchase and own their domain and relevant third-party accounts. Depending on the project, separate costs may include:</p>
      <ul className="growth-check-grid"><li>Domain registration and renewal</li><li>Paid hosting or deployment plan</li><li>Business email</li><li>Form or transactional-email provider</li><li>Booking-provider subscription</li><li>Payment-processing and transaction fees</li><li>SMS, email, WhatsApp, or other messaging charges</li><li>Premium fonts, photos, software, or licenses</li><li>POS hardware and peripherals</li><li>POS, inventory, or channel-provider subscription</li><li>BIR accreditation or provider processes where applicable</li><li>Maintenance and support plan</li><li>Future content, pages, or integrations</li></ul>
      <p>Ask the provider to identify which costs are one-time, monthly, annual, transaction-based, usage-based, or paid directly to another company.</p>
      <p>Client ownership matters. Your agreement should state who owns the domain, accounts, approved content, delivered files, and access after handover.</p>
    </GrowthSection>

    <GrowthSection title="When a lower-cost website is the right choice.">
      <p>A smaller website is not automatically an inferior decision. It can be the most practical first phase when the business:</p>
      <ul><li>Has a focused offer</li><li>Needs only a few pages</li><li>Already handles inquiries well through one monitored channel</li><li>Does not need a contact-form backend</li><li>Can provide finished copy and images</li><li>Does not require booking, payment, inventory, or custom workflows</li><li>Has a clear plan for updating information</li></ul>
      <p>In that situation, a focused static website may create a credible owned presence without forcing the business to maintain tools it does not need.</p>
      <p>The mistake is not choosing a smaller site. The mistake is expecting a small static scope to behave like a booking platform, CRM, ecommerce operation, POS, or custom application.</p>
    </GrowthSection>

    <GrowthSection title="When you need more than a basic website." className="growth-tinted">
      <p>A more complete scope may be justified when:</p>
      <ul><li>Visitors need detailed service information before contacting you</li><li>The business needs delivered and validated inquiries</li><li>Customers need to select services, dates, staff, rooms, or resources</li><li>Staff must confirm availability or reservations</li><li>The site must connect to an approved provider</li><li>Multiple people need access to operational records</li><li>The business needs permissions, approvals, reports, or history</li><li>Existing records must be migrated</li><li>The project has legal, privacy, tax, security, or industry requirements</li></ul>
      <p>These needs do not always require custom software. An established provider may be more appropriate. Discovery should determine the simplest system that can support the validated workflow.</p>
    </GrowthSection>

    <GrowthSection title="Questions to ask before accepting a website proposal.">
      <p>Use these questions to compare scopes rather than comparing price alone:</p>
      <ol><li><strong>Which exact pages and features are included?</strong></li><li><strong>Who supplies and approves the copy, images, logo, rates, and policies?</strong></li><li><strong>Is the design customized, template-based, or a combination?</strong></li><li><strong>Does the quote include a contact form, and where are inquiries delivered?</strong></li><li><strong>Which integrations are included and technically validated?</strong></li><li><strong>Who owns the domain, hosting, third-party accounts, and delivered access?</strong></li><li><strong>Which subscriptions, fees, licenses, and hardware are separate?</strong></li><li><strong>How many revision rounds are included?</strong></li><li><strong>What testing, training, documentation, and handover are included?</strong></li><li><strong>What happens if a provider changes or an integration stops working?</strong></li><li><strong>Is maintenance included, optional, or unavailable?</strong></li><li><strong>What counts as a change in scope?</strong></li><li><strong>What must the client deliver, and by when?</strong></li><li><strong>What claims or results does the provider refuse to guarantee?</strong></li></ol>
      <p>A trustworthy proposal should make important boundaries easier to understand, not hide them in vague feature labels.</p>
    </GrowthSection>

    <GrowthSection title="Warning signs in an unusually cheap or unclear quote." className="growth-dark">
      <p>A low price is not automatically a problem. It becomes risky when the quote leaves important responsibilities unanswered.</p>
      <p>Watch for:</p>
      <ul><li>No written page or feature scope</li><li>No explanation of domain or account ownership</li><li>“Unlimited revisions” without a review process</li><li>Guaranteed first-page Google rankings</li><li>Booking, payment, POS, or inventory promises without naming the provider or workflow</li><li>A “custom system” price that does not define users, data, rules, testing, or support</li><li>Hidden monthly fees or accounts controlled only by the developer</li><li>No plan for forms, spam, error states, or inquiry delivery</li><li>No mobile review, accessibility consideration, or acceptance testing</li><li>Fake portfolio projects, copied content, or unverifiable results</li><li>No handover, credentials, documentation, or support boundary</li></ul>
      <p>Ask for clarification before paying a deposit. If a key promise cannot be written as a testable requirement, it is not yet a reliable project commitment.</p>
    </GrowthSection>

    <GrowthSection title="How to choose a realistic first phase.">
      <p>Start with the most important job the website must do.</p>
      <ul><li><strong>Establish credibility and direct visitors to a monitored channel:</strong> consider a focused static website.</li><li><strong>Explain several services and receive structured inquiries:</strong> consider a business website.</li><li><strong>Let customers choose an appointment or resource through a supported provider:</strong> consider a booking website.</li><li><strong>Present rooms or packages and manage a clear reservation handoff:</strong> consider a hospitality website.</li><li><strong>Connect operational records, roles, approvals, or reports:</strong> begin with workflow discovery before choosing an established platform or custom development.</li></ul>
      <p>Then define what can wait. A second phase can add pages, content, integrations, automation, or custom operations after the first version is working and the business has better information.</p>
      <p>Northstar’s Free Systems Audit is designed to identify that first phase without assuming every business needs the largest system.</p>
      <TextLinks><InlineLink href="/how-it-works">See how Northstar projects work</InlineLink><InlineLink href="/projects">View selected Northstar projects</InlineLink></TextLinks>
    </GrowthSection>

    <GrowthSection title="Compare the current options.">
      <Disclosure><p>Review <InlineLink href="/packages">Northstar’s current website packages</InlineLink>, <InlineLink href="/services/websites">website design and development</InlineLink>, <InlineLink href="/services/booking">online booking systems</InlineLink>, and <InlineLink href="/industries/resorts-hotels">resort and hotel website design</InlineLink>.</p></Disclosure>
    </GrowthSection>
  </GrowthPageShell>;
}
